### ISSUE TITLE
Error when open gradle-profiler project sync

### ISSUE THREAD

**Issue by NightXlt** [gradle/gradle-profiler#393]
# Error
Using dependency catalogs requires the activation of the matching feature preview.
See the documentation at https://docs.gradle.org/7.3.2/userguide/platforms.html#sub:central-declaration-of-dependencies

# Try
I have already read above doc, but I found set `enableFeaturePreview("VERSION_CATALOGS")` is also invalid

Thanks so much for your reply!

**Comment by asodja** [comment]
Thanks for your interest in `gradle`. You probably don't use the correct version of `gradle`. Version catalog is a feature that requires Gradle 7.0 or later. You either have wrong `gradle` installed on your machine and the wrong version is set in `gradle/wrapper/gradle-wrapper.properties`.


This is all I can tell from that error.  Since this is not an issue with `gradle-profiler` I will close the issue. If you have issue with `Version Catalog` please open an issue to `gradle/gradle` project.
