### ISSUE TITLE
Test failures with Oracle Java 8, new Intel mac

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle-profiler#469]
https://builds.gradle.org/buildConfiguration/GradleProfiler_MacOSJava8/60607566?hideProblemsFromDependencies=false&hideTestsFromDependencies=true

Seems to be some incompatibility on new Intel Mac (Ventura).

**Comment by asodja** [comment]
So it seems we get error code 137 when starting an Android Studio from gradle-profiler. How we start Android Studio:
- we download Android Studio distribution (Gradle tasks)
- in profiler we start Android Studio as:
```
/Users/tcagent1/agent/work/7b79572c01edd19a/build/android-studio/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java -cp <classpath> com.intellij.idea.Main <test project>
```
via [ProcessBuilder](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html). And it exits with error code 137, but I could get any message why is that.

I suspected that there is OOM issue and OS kills the process. So then tried to run just:
```
/Users/tcagent1/agent/work/7b79572c01edd19a/build/android-studio/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java -version
```
That should just print the java version. But I also got error code 137. From that, I believe memory is not an issue but might be an issue with permission. So maybe OS kills the process since the user doesn't have permission to start it.
